### ISSUE TITLE
there is some thing wrong,好像说什么不是有效的32位程序

### ISSUE THREAD

**Issue by sugaredboy** [NTUYWANG103/APEX_AIMBOT#115]
Traceback (most recent call last):
  File "C:\Users\lenovo\Desktop\APEX_AIMBOT-master\apex.py", line 1, in <module>
    from AimBot import AimBot
  File "C:\Users\lenovo\Desktop\APEX_AIMBOT-master\AimBot.py", line 12, in <module>
    from mouse_driver.MouseMove import mouse_move
  File "C:\Users\lenovo\Desktop\APEX_AIMBOT-master\mouse_driver\MouseMove.py", line 1, in <module>
    import mouse_driver.ghub_mouse as ghub
  File "C:\Users\lenovo\Desktop\APEX_AIMBOT-master\mouse_driver\ghub_mouse.py", line 14, in <module>
    gm = CDLL(dlldir)
  File "D:\nb\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

还有我没罗技鼠标咋办

**Comment by PlutoNameless** [comment]
Requires only Ghub drivers, not related to Logitech mice.
Please make sure the environment and driver fulfill the conditions.

**Comment by sugaredboy** [comment]
thanks，
