### ISSUE TITLE
I want to use my own best_apex.onnx file model but not working,please help me!

### ISSUE THREAD

**Issue by soapboss** [NTUYWANG103/APEX_AIMBOT#119]
I want to use my own best_apex.onnx file model. How should I uncomment the encryption code and which file the encryption code is in?

**Comment by PlutoNameless** [comment]
Search for 'cryptography' in the project to retrieve the corresponding code

**Comment by soapboss** [comment]
it shows:

``
[11/19/2023-17:56:23] [TRT] [I] [MemUsageChange] Init CUDA: CPU +5, GPU +0, now: CPU 6259, GPU 1008 (MiB)
[11/19/2023-17:56:28] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +512, GPU +118, now: CPU 7224, GPU 1126 (MiB)
``
``
Traceback (most recent call last):
  File "apex.py", line 17, in <module>
    apex = ApexAimBot(config_path='configs/apex.yaml', onnx_path='weights/best_apex.onnx', engine_path='weights/best_apex.trt')
``
``
  File "apex.py", line 8, in __init__
    super().__init__(config_path, onnx_path, engine_path)
``
``
  File "C:\Users\soapb\Documents\APEX_AIMBOT-master\APEX_AIMBOT-master\AimBot.py", line 24, in __init__
    self.build_trt_model(onnx_path, engine_path)
``
``
  File "C:\Users\soapb\Documents\APEX_AIMBOT-master\APEX_AIMBOT-master\AimBot.py", line 65, in build_trt_model
    export_to_trt(onnx=onnx_path, engine=engine_path)
``
``
  File "C:\Users\soapb\Documents\APEX_AIMBOT-master\APEX_AIMBOT-master\tensorrt_python\export_to_trt.py", line 290, in export_to_trt
    builder.create_network(args.onnx, args.end2end, args.conf_thres, args.iou_thres, args.max_det, args.encryp_password)
``
``
  File "C:\Users\soapb\Documents\APEX_AIMBOT-master\APEX_AIMBOT-master\tensorrt_python\export_to_trt.py", line 130, in create_network
``
``
    onnx_data = fw.decrypt(f.read())
``
``
  File "C:\Users\soapb\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\fernet.py", line 86, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
``
``
  File "C:\Users\soapb\AppData\Local\Programs\Python\Python37\lib\site-packages\cryptography\fernet.py", line 122, in _get_unverified_token_data
``
``
 raise InvalidToken
``
``
cryptography.fernet.InvalidToken
``

Sir , I still cant found which code going wrong

**Comment by PlutoNameless** [comment]
If you remove the encryption in your code, then you shouldn't use the models inside the project.

**Comment by soapboss** [comment]
I didn't remove encrypted code yet,can you discribe specifically which file or which code line should be removed
