### ISSUE TITLE
TypeError: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by SYIRUL94** [NTUYWANG103/APEX_AIMBOT#125]
(apex) C:\Users\syahi\OneDrive\Desktop\APEX_AIMBOT-master>python apex.py
-------The first time the model is being built, the waiting time is long (about 15 mins), and there will be a text
message when it is finished.-------
[12/08/2023-14:14:45] [TRT] [I] [MemUsageChange] Init CUDA: CPU +2, GPU +0, now: CPU 11398, GPU 1050 (MiB)
[12/08/2023-14:14:45] [TRT] [E] 6: [libLoader.h::nvinfer1::rt::DynamicLibrary::DynamicLibrary::54] Error Code 6: Internal Error (Unable to load library: nvinfer_builder_resource.dll)
Traceback (most recent call last):
  File "apex.py", line 17, in <module>
    apex = ApexAimBot(config_path='configs/apex.yaml', onnx_path='weights/best_apex.onnx', engine_path='weights/best_apex.trt')
  File "apex.py", line 8, in __init__
    super().__init__(config_path, onnx_path, engine_path)
  File "C:\Users\syahi\OneDrive\Desktop\APEX_AIMBOT-master\AimBot.py", line 24, in __init__
    self.build_trt_model(onnx_path, engine_path)
  File "C:\Users\syahi\OneDrive\Desktop\APEX_AIMBOT-master\AimBot.py", line 65, in build_trt_model
    export_to_trt(onnx=onnx_path, engine=engine_path)
  File "C:\Users\syahi\OneDrive\Desktop\APEX_AIMBOT-master\tensorrt_python\export_to_trt.py", line 289, in export_to_trt
    builder = EngineBuilder(args.verbose, args.workspace)
  File "C:\Users\syahi\OneDrive\Desktop\APEX_AIMBOT-master\tensorrt_python\export_to_trt.py", line 109, in __init__
    self.builder = trt.Builder(self.trt_logger)
TypeError: pybind11::init(): factory function returned nullptr

please help

**Comment by NS7IQ** [comment]
I have the same problem. Did you fix it?
