### ISSUE TITLE
ModuleNotFound

### ISSUE THREAD

**Issue by 7862248424638247** [NTUYWANG103/APEX_AIMBOT#22]
Traceback (most recent call last):
  File "csgo.py", line 1, in <module>
    from AimBot import AimBot
  File "C:\Desktop\APEX_AIMBOT-master\AimBot.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by 7862248424638247** [comment]
Also is there a way for this to work with other resolutions? For example I want it to work on 1280x960 but then its locking on nothing in the sky or doesnt work at all

**Comment by NTUYWANG103** [comment]
set to boardless mode for game
