### ISSUE TITLE
是否只能使用文件提供的权重？这段是否加密了

### ISSUE THREAD

**Issue by unicorn5514** [NTUYWANG103/APEX_AIMBOT#39]
我尝试使用自己的权重但是却出现了解密失败。
F:\py3.8\python.exe F:\aim\yolov7aim\cod19.py 
Traceback (most recent call last):
  File "F:\aim\yolov7aim\cod19.py", line 17, in <module>
    apex = ApexAimBot(config_path='configs/cod19.yaml', onnx_path='weights/cod19.onnx', engine_path='weights/cod19.trt')
  File "F:\aim\yolov7aim\cod19.py", line 8, in __init__
    super().__init__(config_path, onnx_path, engine_path)
  File "F:\aim\yolov7aim\AimBot.py", line 34, in __init__
    self.engine = BaseEngine(engine_path)
  File "F:\aim\yolov7aim\utils\InferenceEngine.py", line 21, in __init__
    serialized_engine = fw.decrypt(f.read())
  File "F:\py3.8\lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "F:\py3.8\lib\site-packages\cryptography\fernet.py", line 121, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken

**Comment by actich** [comment]
![image](https://user-images.githubusercontent.com/108247720/233828370-308f6742-dc49-47fb-a980-08d79e890dfe.png)
T_T

**Comment by NTUYWANG103** [comment]
All codes are open sourced, you can use your own weight

**Comment by actich** [comment]
> 

Thank you!   It's working
