### ISSUE TITLE
我遇到一些问题

### ISSUE THREAD

**Issue by iu6888** [NTUYWANG103/APEX_AIMBOT#44]
Traceback (most recent call last):
  File "E:\xz\APEX_AIMBOT-master\APEX_AIMBOT-master\AimBot.py", line 13, in <module>
    from utils.InferenceEngine import BaseEngine, precise_sleep
  File "E:\xz\APEX_AIMBOT-master\APEX_AIMBOT-master\utils\InferenceEngine.py", line 7, in <module>
    import pycuda.driver as cuda
  File "E:\xz\APEX_AIMBOT-master\venv\lib\site-packages\pycuda\driver.py", line 65, in <module>
    from pycuda._driver import *  # noqa
ImportError: DLL load failed while importing _driver: 找不到指定的程序。

**Comment by Thiece** [comment]
Make sure that the entire environment is installed according to the tutorial;
If you don't know how to program or install, try asking ChatGPT
