### ISSUE TITLE
Change code to support yolov8

### ISSUE THREAD

**Issue by modu82** [NTUYWANG103/APEX_AIMBOT#58]
Onnx conversion Tensorrt updated support for YOLOv8，How should I modify the export code

**Comment by modu82** [comment]
I tried to remove the encryption in the code and directly import the converted model, but it was not successful

**Comment by eka2122** [comment]
hey bro do you have discord? I need help

**Comment by modu82** [comment]
> hey bro do you have discord? I need help

What can I help you with

**Comment by modu82** [comment]
i try change this code
```
with open(engine_path, "rb") as f:
            serialized_engine = fw.decrypt(f.read())
            
        engine = runtime.deserialize_cuda_engine(serialized_engine)
```
but engine is not Unable to obtain correctly serialized_engine

**Comment by eka2122** [comment]
> > hey bro do you have discord? I need help
> 
> What can I help you with

about the config, my aimbot can't work? even though everything is running according to the instructions

**Comment by modu82** [comment]
> 



> > > hey bro do you have discord? I need help
> > 
> > 
> > What can I help you with
> 
> about the config, my aimbot can't work? even though everything is running according to the instructions

I have some basic debugging methods:
Set visualization to true
Set Apex to Window Mode
Check for normal operation in visualization

**Comment by modu82** [comment]
> > > hey bro do you have discord? I need help
> > 
> > 
> > What can I help you with
> 
> about the config, my aimbot can't work? even though everything is running according to the instructions

and If your terminal outputs locking information normally, then the program should be working properly

**Comment by eka2122** [comment]
> > > > hey bro do you have discord? I need help
> > > 
> > > 
> > > What can I help you with
> > 
> > 
> > about the config, my aimbot can't work? even though everything is running according to the instructions
> 
> and If your terminal outputs locking information normally, then the program should be working properly

i am bad in english can you give me your aimbot configs?

**Comment by modu82** [comment]
> > > > > hey bro do you have discord? I need help
> > > > 
> > > > 
> > > > What can I help you with
> > > 
> > > 
> > > about the config, my aimbot can't work? even though everything is running according to the instructions
> > 
> > 
> > and If your terminal outputs locking information normally, then the program should be working properly
> 
> i am bad in english can you give me your aimbot configs?

中文会不

**Comment by eka2122** [comment]
> > > > > > hey bro do you have discord? I need help
> > > > > 
> > > > > 
> > > > > What can I help you with
> > > > 
> > > > 
> > > > about the config, my aimbot can't work? even though everything is running according to the instructions
> > > 
> > > 
> > > and If your terminal outputs locking information normally, then the program should be working properly
> > 
> > 
> > i am bad in english can you give me your aimbot configs?
> 
> 中文会不

I'm from Indonesia

**Comment by modu82** [comment]
Normally, the configuration file does not need to be modified，Please pay attention to the terminal information output after running Apex.py

**Comment by modu82** [comment]
> > > > > > > hey bro do you have discord? I need help
> > > > > > 
> > > > > > 
> > > > > > What can I help you with
> > > > > 
> > > > > 
> > > > > about the config, my aimbot can't work? even though everything is running according to the instructions
> > > > 
> > > > 
> > > > and If your terminal outputs locking information normally, then the program should be working properly
> > > 
> > > 
> > > i am bad in english can you give me your aimbot configs?
> > 
> > 
> > 中文会不
> 
> I'm from Indonesia


Normally, the configuration file does not need to be modified，Please pay attention to the terminal information output after running Apex.py

**Comment by modu82** [comment]
> > > > > hey bro do you have discord? I need help
> > > > 
> > > > 
> > > > What can I help you with
> > > 
> > > 
> > > about the config, my aimbot can't work? even though everything is running according to the instructions
> > 
> > 
> > and If your terminal outputs locking information normally, then the program should be working properly
> 
> i am bad in english can you give me your aimbot configs?

More information is needed to know where the problem lies

**Comment by eka2122** [comment]
> > > > > > hey bro do you have discord? I need help
> > > > > 
> > > > > 
> > > > > What can I help you with
> > > > 
> > > > 
> > > > about the config, my aimbot can't work? even though everything is running according to the instructions
> > > 
> > > 
> > > and If your terminal outputs locking information normally, then the program should be working properly
> > 
> > 
> > i am bad in english can you give me your aimbot configs?
> 
> More information is needed to know where the problem lies

yes the terminal is not running! what is the button to enable aimbot by default

**Comment by modu82** [comment]
I encountered this problem when using my own model

```
Traceback (most recent call last):
  File "D:\Python\APEX_AIMBOT\apex.py", line 17, in <module>
    apex = ApexAimBot(config_path='configs/apex.yaml', onnx_path='weights/best_apex.onnx', engine_path='weights/best_apex.trt')
  File "D:\Python\APEX_AIMBOT\apex.py", line 8, in __init__
    super().__init__(config_path, onnx_path, engine_path)
  File "D:\Python\APEX_AIMBOT\AimBot.py", line 38, in __init__
    self.speed_test()
  File "D:\Python\APEX_AIMBOT\AimBot.py", line 106, in speed_test
    self.engine.inference(img)
  File "D:\Python\APEX_AIMBOT\utils\InferenceEngine.py", line 57, in inference
    num, final_boxes, final_scores, final_cls_inds = self.forward(img)
ValueError: not enough values to unpack (expected 4, got 1)
```

**Comment by modu82** [comment]
> To the best of my knowledge, the YOLOv5's ONNX doesn't include NMS (Non-Maximum Suppression), and I'm not entirely sure if there have been any adjustments made in YOLOv8. In YOLOv7, we used NMS End 2 End for ONNX export. If you need to make other adjustments, you might have to consider implementing NMS.

I encountered this problem when using my own model，Do I need any special operations when building the model


```
Traceback (most recent call last):
  File "D:\Python\APEX_AIMBOT\apex.py", line 17, in <module>
    apex = ApexAimBot(config_path='configs/apex.yaml', onnx_path='weights/best_apex.onnx', engine_path='weights/best_apex.trt')
  File "D:\Python\APEX_AIMBOT\apex.py", line 8, in __init__
    super().__init__(config_path, onnx_path, engine_path)
  File "D:\Python\APEX_AIMBOT\AimBot.py", line 38, in __init__
    self.speed_test()
  File "D:\Python\APEX_AIMBOT\AimBot.py", line 106, in speed_test
    self.engine.inference(img)
  File "D:\Python\APEX_AIMBOT\utils\InferenceEngine.py", line 57, in inference
    num, final_boxes, final_scores, final_cls_inds = self.forward(img)
ValueError: not enough values to unpack (expected 4, got 1)
```

**Comment by xiazaipw** [comment]
hi bro did you solve it? I also encountered this problem.Unable to use own model ONNX, convert TRT

**Comment by Tr3yWay996** [comment]
> Onnx conversion Tensorrt updated support for YOLOv8，How should I modify the export code

So ? anything new ? any compatibility with AMD gpus ?
