### ISSUE TITLE
Unable to use own model ONNX, convert TRT

### ISSUE THREAD

**Issue by xiazaipw** [NTUYWANG103/APEX_AIMBOT#62]
Unable to use own model ONNX, convert TRT  Hi bro I have encountered this problem, please tell me how to solve it. Thanks,

**Comment by xiazaipw** [comment]
PS D:\GAMES\yolov7-cf> & C:/Python39/python.exe "d:/GAMES/yolov7-cf/Cross Fire.py"
---------------------模型制作中，第一次等待时间较长(大约 15 mins), 完成后会有文字提示---------------------
[05/24/2023-09:47:37] [TRT] [I] [MemUsageChange] Init CUDA: CPU +4, GPU +0, now: CPU 4095, GPU 921 (MiB)
[05/24/2023-09:47:43] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +217, GPU +40, now: CPU 5324, GPU 961 (MiB)
Traceback (most recent call last):
  File "d:\GAMES\yolov7-cf\Cross Fire.py", line 17, in <module>
    apex = ApexAimBot(config_path='configs/Cross Fire.yaml', onnx_path='weights/cf.onnx', engine_path='weights/cf.trt')
  File "d:\GAMES\yolov7-cf\Cross Fire.py", line 8, in __init__
    super().__init__(config_path, onnx_path, engine_path)
  File "d:\GAMES\yolov7-cf\AimBot.py", line 26, in __init__
    self.build_trt_model(onnx_path, engine_path)
  File "d:\GAMES\yolov7-cf\AimBot.py", line 67, in build_trt_model
    export_to_trt(onnx=onnx_path, engine=engine_path)
  File "d:\GAMES\yolov7-cf\tensorrt_python\export_to_trt.py", line 290, in export_to_trt
    builder.create_network(args.onnx, args.end2end, args.conf_thres, args.iou_thres, args.max_det, args.encryp_password)
  File "d:\GAMES\yolov7-cf\tensorrt_python\export_to_trt.py", line 130, in create_network
    onnx_data = fw.decrypt(f.read())
  File "C:\Python39\lib\site-packages\cryptography\fernet.py", line 85, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "C:\Python39\lib\site-packages\cryptography\fernet.py", line 121, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.Invalid

**Comment by xiazaipw** [comment]
Using ONNX that comes with the source code, you can convert TRT

**Comment by Thiece** [comment]
Remove the encrypted part of the model from the source code

**Comment by xiazaipw** [comment]
AimBot.py?Is it in here?

**Comment by xiazaipw** [comment]
老哥，能否告诉下，怎么禁用加密部分，谢谢，

**Comment by wakk123** [comment]
> 老哥，能否告诉下，怎么禁用加密部分，谢谢，

兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。

**Comment by xiazaipw** [comment]
> > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> 
> 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。

多谢老哥，不过已经删除了，。谢谢你的解答。感谢。

**Comment by xiazaipw** [comment]
> > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> 
> 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。

 老兄玩什么游戏，方便的话一起嘛，我扣扣136001

**Comment by wakk123** [comment]
> > > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> > 
> > 
> > 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。
> 
> 老兄玩什么游戏，方便的话一起嘛，我扣扣136001

玩的cf。

**Comment by wakk123** [comment]
> > > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> > 
> > 
> > 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。
> 
> 老兄玩什么游戏，方便的话一起嘛，我扣扣136001

加上不。扣扣搜索不到。

**Comment by xiazaipw** [comment]
> > > > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> > > 
> > > 
> > > 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。
> > 
> > 
> > 老兄玩什么游戏，方便的话一起嘛，我扣扣136001
> 
> 加上不。扣扣搜索不到。

 忘记了。我没有开启，现在好了

**Comment by wakk123** [comment]
> 



> > > > > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> > > > 
> > > > 
> > > > 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。
> > > 
> > > 
> > > 老兄玩什么游戏，方便的话一起嘛，我扣扣136001
> > 
> > 
> > 加上不。扣扣搜索不到。
> 
> 忘记了。我没有开启，现在好了

加你了。

**Comment by wgyahh** [comment]
> 从源代码中删除模型的加密部分

请问能详细说一下怎么操作才能使用自己的模型吗，万分感谢。QAQ

**Comment by wgyahh** [comment]
> > 从源代码中删除模型的加密部分
> 
> 请提问能详细说一下怎么操作才能使用自己的模型吗，万分感谢。QAQ

或者简单说下删除哪一段模型加密的代码，ORZ

**Comment by wgyahh** [comment]
> > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> 
> 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。

能请教一下用cryptograghy给模型加密的具体步骤吗。找了很久没有找到怎么加密。这个环境确实自带cryptograghy

**Comment by EIJ49** [comment]
> > > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> > 
> > 
> > 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。
> 
> 能请教一下用cryptograghy给模型加密的具体步骤吗。找了很久没有找到怎么加密。这个环境确实自带cryptograghy

You can try to encrypt using the author's key.
你可以尝试使用作者的密钥进行加密。
Code：
from cryptography.fernet import Fernet
# enter the key in ''.  ## 在 ' ' 中输入密钥
key = b'-----key-----'
# onnx file path that requires encryption.  ## 需要加密的onnx文件路径。
model_file = ['./xxx.onnx']
# encrypted file storage path.  ## 加密文件存储路径。
new_model_file = ['./best_apex.onnx']
# Model encryption  ## 模型加密
for i in range(1):
    with open(new_model_file[i], 'wb') as ew:
        content = open(model_file[i], 'rb').read()
        encrypted_content = Fernet(key).encrypt(content)
        print(encrypted_content)

**Comment by EIJ49** [comment]
> > > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> > 
> > 
> > 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。
> 
> 能请教一下用cryptograghy给模型加密的具体步骤吗。找了很久没有找到怎么加密。这个环境确实自带cryptograghy

You can try to encrypt using the author's key.
你可以尝试使用作者的密钥进行加密。
Code：
from cryptography.fernet import Fernet
key = b'-----key-----'  # enter the key in ''.   ## 在 ' ' 中输入密钥
model_file = ['./xxx.onnx']  # onnx file path that requires encryption.  ## 需要加密的onnx文件路径。
new_model_file = ['./best_apex.onnx']  # encrypted file storage path.  ## 加密文件存储路径。
for i in range(1):  # Model encryption  ## 模型加密
    with open(new_model_file[i], 'wb') as ew:
        content = open(model_file[i], 'rb').read()
        encrypted_content = Fernet(key).encrypt(content)
        print(encrypted_content)

**Comment by soapboss** [comment]
> > > 老哥，能否告诉下，怎么禁用加密部分，谢谢，
> > 
> > 
> > 兄弟，你可以通过cryptography库的加密进行模型加密，然后修改源代码里面的密钥即可使用自己的模型。
> 
> 多谢老哥，不过已经删除了，。谢谢你的解答。感谢。

你好老哥 ，可以告诉我你删的是哪一个文件的哪一个代码吗
