### ISSUE TITLE
error，helps

### ISSUE THREAD

**Issue by liu19666** [NTUYWANG103/APEX_AIMBOT#91]
Traceback (most recent call last):
  File "apex.py", line 19, in <module>
    apex.forward()
  File "D:\Chrome Download\APEX_AIMBOT-master\AimBot.py", line 198, in forward
    fps_track = 1/(time.time()-start_time)
ZeroDivisionError: float division by zero

怎么办

**Comment by AmatoGiulio** [comment]
fps_track = (time.time()-start_time) and 1/ (time.time()-start_time)
fixed in my fork
